language: c

compiler:
    - gcc

install:
    - sudo apt-get install libacl1-dev
script:
    - make -C libft libft.a -j
    - make -C libft libft_debug.a -j
    - make -C libft libft.so -j
    - make all -j
    - make debug -j
